env:
  name: Gridworld
  params:
    grid_size: 10
    max_steps: 50
    goal_pos: null
    start_pos: null
    size_obs: false
    random_start: false
    random_goal: false

algo:
  name: sac
  params:
    hidden_dim: 64
    hidden_layers: 2
    learning_rate: 0.00003
    gamma: 0.99                        # Discount factor
    tau: 0.005                         # How much to update the target networks at each update
    alpha: 0.2                        # Entropy reg coef
    automatic_entropy_tuning: false

device: auto

training:
  total_steps: 50000
  batch_size: 32
  buffer_capacity: 50000
  buffer_sequence_length: null
  start_training_after: 500
  updates_per_step: 1
  seed: 0

evaluation:
  eval_every_episodes: 10
  num_episodes: 1
  record_video: true
  video_every_calls: 4

checkpoint:
  checkpoint_every_steps: 1000

logging:
  wandb_project: jared-rl
  wandb_entity: murphey-lab-nu
