# Look at Appendix D in SAC paper
env:
  name: PointGoal
  params:
    plane_size: 10
    max_steps: 100
    max_speed: 0.2
    goal_threshold: 0.2
    goal_pos: null
    start_pos: null
    random_start: true
    random_goal: true

algo:
  name: sac
  params:
    hidden_dim: 64
    hidden_layers: 2
    learning_rate: 0.0003
    gamma: 0.99                        # Discount factor
    tau: 0.005                         # How much to update the target networks at each update
    alpha: 0.2                         # Entropy reg coef
    automatic_entropy_tuning: true

training:
  total_steps: 10000
  batch_size: 128
  buffer_capacity: 10000
  buffer_sequence_length: null
  start_training_after: 500
  updates_per_step: 1
  seed: 0

evaluation:
  eval_every_episodes: 10
  num_episodes: 1
  record_video: true
  video_every_calls: 1

checkpoint:
  checkpoint_every_steps: 1000

logging:
  wandb_project: jared-rl
  wandb_entity: murphey-lab-nu
