env:
  name: MountainCarContinuous
  params: {}

algo:
  name: sac
  params:
    hidden_dim: 64
    hidden_layers: 2
    learning_rate: 0.00003
    gamma: 0.98
    tau: 0.005
    alpha: 0.3
    automatic_entropy_tuning: false

training:
  total_steps: 100000
  batch_size: 32
  buffer_capacity: 100000
  buffer_sequence_length: null
  start_training_after: 500
  updates_per_step: 1
  seed: 0

evaluation:
  eval_every_episodes: 20
  num_episodes: 1
  record_video: true
  video_every_calls: 1

checkpoint:
  checkpoint_every_steps: 2000

logging:
  wandb_project: jared-rl
  wandb_entity: murphey-lab-nu